// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ManagerCallbackRequest ...
type ManagerCallbackRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

// Reset ...
func (m *ManagerCallbackRequest) Reset() { *m = ManagerCallbackRequest{} }

// String ...
func (m *ManagerCallbackRequest) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*ManagerCallbackRequest) ProtoMessage() {}

// Descriptor ...
func (*ManagerCallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_7208abb6a20b929c, []int{0}
}

// XXX_Unmarshal ...
func (m *ManagerCallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerCallbackRequest.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *ManagerCallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerCallbackRequest.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (dst *ManagerCallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerCallbackRequest.Merge(dst, src)
}

// XXX_Size ...
func (m *ManagerCallbackRequest) XXX_Size() int {
	return xxx_messageInfo_ManagerCallbackRequest.Size(m)
}

// XXX_DiscardUnknown ...
func (m *ManagerCallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerCallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerCallbackRequest proto.InternalMessageInfo

// GetID ...
func (m *ManagerCallbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetDetail ...
func (m *ManagerCallbackRequest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

// ManagerReply ...
type ManagerReply struct {
	Code                 int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               *ManagerReplyDetail `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

// Reset ...
func (m *ManagerReply) Reset() { *m = ManagerReply{} }

// String ...
func (m *ManagerReply) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*ManagerReply) ProtoMessage() {}

// Descriptor ...
func (*ManagerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_7208abb6a20b929c, []int{1}
}

// XXX_Unmarshal ...
func (m *ManagerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerReply.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *ManagerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerReply.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (dst *ManagerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerReply.Merge(dst, src)
}

// XXX_Size ...
func (m *ManagerReply) XXX_Size() int {
	return xxx_messageInfo_ManagerReply.Size(m)
}

// XXX_DiscardUnknown ...
func (m *ManagerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerReply.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerReply proto.InternalMessageInfo

// GetCode ...
func (m *ManagerReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// GetMessage ...
func (m *ManagerReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetDetail ...
func (m *ManagerReply) GetDetail() *ManagerReplyDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

// ManagerReplyDetail ...
type ManagerReplyDetail struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Json                 string   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

// Reset ...
func (m *ManagerReplyDetail) Reset() { *m = ManagerReplyDetail{} }

// String ...
func (m *ManagerReplyDetail) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*ManagerReplyDetail) ProtoMessage() {}

// Descriptor ...
func (*ManagerReplyDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_7208abb6a20b929c, []int{2}
}

// XXX_Unmarshal ...
func (m *ManagerReplyDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerReplyDetail.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *ManagerReplyDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerReplyDetail.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (dst *ManagerReplyDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerReplyDetail.Merge(dst, src)
}

// XXX_Size ...
func (m *ManagerReplyDetail) XXX_Size() int {
	return xxx_messageInfo_ManagerReplyDetail.Size(m)
}

// XXX_DiscardUnknown ...
func (m *ManagerReplyDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerReplyDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerReplyDetail proto.InternalMessageInfo

// GetID ...
func (m *ManagerReplyDetail) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetJson ...
func (m *ManagerReplyDetail) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagerCallbackRequest)(nil), "proto.ManagerCallbackRequest")
	proto.RegisterType((*ManagerReply)(nil), "proto.ManagerReply")
	proto.RegisterType((*ManagerReplyDetail)(nil), "proto.ManagerReplyDetail")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerServiceClient interface {
	Back(ctx context.Context, in *ManagerCallbackRequest, opts ...grpc.CallOption) (*ManagerReply, error)
}

type managerServiceClient struct {
	cc *grpc.ClientConn
}

// NewManagerServiceClient ...
func NewManagerServiceClient(cc *grpc.ClientConn) ManagerServiceClient {
	return &managerServiceClient{cc}
}

// Back ...
func (c *managerServiceClient) Back(ctx context.Context, in *ManagerCallbackRequest, opts ...grpc.CallOption) (*ManagerReply, error) {
	out := new(ManagerReply)
	err := c.cc.Invoke(ctx, "/proto.ManagerService/Back", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
type ManagerServiceServer interface {
	Back(context.Context, *ManagerCallbackRequest) (*ManagerReply, error)
}

// RegisterManagerServiceServer ...
func RegisterManagerServiceServer(s *grpc.Server, srv ManagerServiceServer) {
	s.RegisterService(&_ManagerService_serviceDesc, srv)
}

func _ManagerService_Back_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Back(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ManagerService/Back",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Back(ctx, req.(*ManagerCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Back",
			Handler:    _ManagerService_Back_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_manager_7208abb6a20b929c) }

var fileDescriptor_manager_7208abb6a20b929c = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0x31, 0xad, 0x38, 0x6a, 0x0f, 0x53, 0x28, 0x51, 0x10, 0x4a, 0x4e, 0x3d, 0x05, 0x5a,
	0x2f, 0x1e, 0x3c, 0x48, 0xcc, 0xa5, 0x07, 0xa5, 0xc4, 0x27, 0xd8, 0x6c, 0x86, 0x35, 0x76, 0x93,
	0xa9, 0xd9, 0xad, 0xe0, 0xdb, 0x8b, 0x9b, 0xb5, 0x58, 0xdb, 0xd3, 0xce, 0x7c, 0xf3, 0xfd, 0xb1,
	0x70, 0xd5, 0x88, 0x56, 0x28, 0xea, 0xd2, 0x4d, 0xc7, 0x96, 0x71, 0xe0, 0x9e, 0xe4, 0x11, 0x26,
	0xcf, 0x3d, 0xfe, 0x24, 0xb4, 0x2e, 0x85, 0x5c, 0x17, 0xf4, 0xb1, 0x25, 0x63, 0x71, 0x04, 0xe1,
	0x32, 0x8f, 0x83, 0x69, 0x30, 0x3b, 0x2f, 0xc2, 0x65, 0x8e, 0x13, 0x18, 0x56, 0x64, 0x45, 0xad,
	0xe3, 0xd0, 0x61, 0x7e, 0x4b, 0x18, 0x2e, 0xbd, 0x43, 0x41, 0x1b, 0xfd, 0x85, 0x08, 0x91, 0xe4,
	0x8a, 0x9c, 0x72, 0x50, 0xb8, 0x19, 0x63, 0x38, 0x6b, 0xc8, 0x18, 0xa1, 0xc8, 0x8b, 0x7f, 0x57,
	0x9c, 0xef, 0x5c, 0x4f, 0xa7, 0xc1, 0xec, 0x62, 0x71, 0xdd, 0xd7, 0x4b, 0xff, 0x5a, 0xe6, 0x8e,
	0xb0, 0x0b, 0xbc, 0x07, 0x3c, 0xbc, 0x1e, 0xd4, 0x45, 0x88, 0xde, 0x0d, 0xb7, 0x3e, 0xcf, 0xcd,
	0x8b, 0x17, 0x18, 0x79, 0xe5, 0x2b, 0x75, 0x9f, 0xb5, 0x24, 0x7c, 0x80, 0x28, 0x13, 0x72, 0x8d,
	0xb7, 0xfb, 0xb1, 0xff, 0xfe, 0xe2, 0x66, 0x7c, 0xa4, 0x55, 0x72, 0x92, 0xcd, 0x21, 0x96, 0xdc,
	0xa4, 0xaa, 0xb6, 0x6f, 0xdb, 0x32, 0x55, 0x5c, 0x49, 0x6e, 0x55, 0x4f, 0xcd, 0xc6, 0xfb, 0x49,
	0xab, 0x1f, 0x70, 0x15, 0x94, 0x43, 0x77, 0xbd, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xdd,
	0x33, 0x78, 0x8e, 0x01, 0x00, 0x00,
}
